### ISSUE TITLE
Combine Sphere.Plugins and Sphere.Core?

### ISSUE THREAD

**Issue by fatcerberus** [Radnen/spherestudio#44]
The way the editor is currently set up, any plugin has to link to both of these (I think).  Should the functionality in Sphere.Plugins be folded into Sphere.Core?

**Comment by Radnen** [comment]
My thought for separating them was so that you could create a plugin only by linking the plugins library. It just so happens that most of them need stuff present in the core library as well (since y'know they work with Sphere filetypes and stuff).

My inspiration came from MonoDevelop and how they had separate library files for their functionality. I may want to keep them separated because I like the organization.

**Comment by fatcerberus** [comment]
I figured that was the rationale.  And for the most part I agree with it--there are really only a few minor components left that can't be accessed through Sphere.Plugins.

We'd have to look and see what else is in Sphere.Core that would be useful for third-party plugins and maybe move it over.

**Comment by fatcerberus** [comment]
I know what might help - adding a dedicated interface for writing plugin options, `ISettings` or similar.  Right now it's directly exposed as `SphereSettings`, which is defined in Core.

**Comment by Radnen** [comment]
I agree with the settings part. I wonder if plugins should write to the one main settings file, or if they have the ability to write to their own separate files.

If you want to implement `ISettings` you can, if not I can do it.

**Comment by fatcerberus** [comment]
I'll implement it.

What I think would be best is either, write each plugin's settings to an INI file matching the plugin ID, or separate INI sections in editor.ini.  The former might be cleaner, though.  If something goes wrong with a plugin's settings, you can just delete it's config file without blowing away everything else.

The current setup of throwing everything into one big key/value list is definitely prone to breakage as the number of plugins grows.  It's better, I think, to sandbox them.

**Comment by Radnen** [comment]
Ok, but there will be a lot of settings files. There should be a convention. Plugins go to the `plugins` directory as normal, and so too their settings. The settings should even be named the same as the plugin's name. So you'd have `plugin_namw.dll` with `plugin_name.ini` next to it.

Like how comment .xml files are stored alongside .dll files with code libraries. In fact, do we want to continue to use .ini?

It may be debatable but would XML be better. Another option is a separate plugins XML file that they can write to. Though it can get cluttered with inactive plugin's settings. But with proper xml namespaces or sections, I'm sure there won't be any clashing going on.

Regardless of the option I still would like the ability for one plugin to read another plugin's settings.

**Comment by fatcerberus** [comment]
I don't know, I like the simplicity of INI files, they're very easy to modify when things go wrong.  XML is great as long as the computer is the only thing touching it, once a human opens the file it loses most of its benefits (I hate having to manually modify VS project files for this reason).  Plus Sphere itself uses an INI-like format for most things (the File object, game.sgm, etc.).

As for conventions, that's pretty much what I was shooting for.  The only thing I think has to be different is that the plugin's INI file can't go alongside the plugin DLL itself, since the plugin directly might not be writable (pre-installed plugins, e.g.)  I would put them in ~/Sphere Studio/Settings, where editor.ini goes now.  Makes them easy to find and edit, too.

**Comment by fatcerberus** [comment]
Here's a first draft of `ISettings`:
https://github.com/Radnen/spherestudio/tree/isettings

It needs some polishing, which is why I have it on its own branch for now.

There is no concept of a plugin hierarchy with this implementation, it's designed to be as generic as possible so as not to paint us into a corner later.  Usage:
```c#
ISettings conf = new Settings("SPK.ini");
int level = conf.GetInteger("deflateLevel", 5);
```

This way each component can create its own INI file and they don't end up clobbering each others' settings, but it's still easy to access the config of a different plugin/component.

**Comment by Radnen** [comment]
I like how generic the system is. It's fine if we don't use XML, INI is much easier to read by a person to edit things manually. (Though XML seems to have a wider spread of use under .NET projects for whatever reason, which is why I thought of it).

Writing plugins to a separate `/settings` folder is a-okay with me. I just didn't want to see the root directory cluttered, hence my desire to also add the `/presets` folder, which could now be folded into the `settings` folder come to think of it (that is, if we want to maintain a generic approach, presets are INI files anyways).

**Comment by fatcerberus** [comment]
Don't do anything with the `ISettings` stuff yet, I have some modifications I need to make it to first.

As for the preset/config separation, this how I'm going to set it up:

* All configuration files are .ini for easy editing by the user.  ~ refers to the user's "My Documents" directory (home folder under Wine)

* Presets store engine paths, project directories and plugin selection.  Nothing else.  Stored in `~\Sphere Studio\Presets`

* INI files store user environment settings such as Load Last Project, color scheme, etc.  Some of these can be moved to the `.ssuser` file in 2.0, but user settings should never go in a preset.  Each plugin gets its own INI file by default.  Stored in `~\Sphere Studio\Settings`

* IPlugin.Initialize() will now get passed an ISettings object referring the the unique INI file for that plugin.

**Comment by fatcerberus** [comment]
The preset overhaul is complete, as well as the conversion of core settings to the `ISettings` interface.  The concrete class is `CoreSettings` and it neatly encapsulates not only the options themselves, but also preset loading.  The preset loading code has thus been moved out of IDEForm.cs.
