### ISSUE TITLE
New IDocumentView interface

### ISSUE THREAD

**Issue by fatcerberus** [Radnen/spherestudio#47]
`IDocumentView` replaces EditorObject for plugins.  Edit controls will derive from this new interface.

A DocumentView has a few main responsibilities:
* Provide a WinForms control to embed in the IDE
* Save to a specified filename (the editor provides the Save dialog)
* Load from a specified file
* Set up for a new document when needed
* Track dirty status
* Serialize view state as a string

That last one is the real strength of this system: it unifies a setup for saving current view of an editor, for example the cursor position and selection in a script.  Previously this would have been handled by the plugin itself, now we can just tell the editor our state and it handles saving and loading it from the `.ssuser` file.

Note that the DocumentView doesn't track its filename.  This is deliberate: We let the editor handle that to keep options open.  Maybe we would want the ability to manage projects in zip files or something in the future. :P  Unlikely, but the generic-ness is welcome regardless.

**Comment by fatcerberus** [comment]
So, the implementation of this is going very well.  There is a new class, `DocumentTab`, which manages such things as Save As, save-on-close, etc.  As a result, editor plugins no longer have to implement their own file dialog handling.

The clunky `TryEditFile` event is gone.  It served its purpose, but will be replaced with a much more flexible system:
```c#
PluginManager.RegisterExtensions(this, "js", "coffee");

public bool OpenDocument(string path, out IDocumentView view)
{
    view = new ScriptEditor();
    view.Load(path);
    return true;
}
```

```c#
// the plugin manager will look at the file extension and see if any plugins are registered
// to handle it.  If one is found, its own OpenDocument() method is called to load the file.
IDocumentView view;
bool opened = PluginManager.OpenDocument(path, out view);
```

OpenDocument() can set `view` to null if the file was opened successfully but doesn't need a document tab.  The Sound Test plugin uses this trick.

**Comment by Radnen** [comment]
I like this, it was something I knew it needed for a long time, but I wasn't sure when to add a dedicated document view to handle file dialogs and the like.

This is a much needed refactorization, thanks! :+1:

**Comment by fatcerberus** [comment]
My efforts so far:
https://github.com/Radnen/spherestudio/tree/document-fx

Tons of stuff is broken right now, but this way you get a preview of the system.  It's pretty awesome.

Oh, and IDEForm.cs got a makeover as well.

**Comment by fatcerberus** [comment]
Okay, bugtest time.  Try out the `document-fx` branch extensively, and let me know of any issues.  This was lots of fun to do!

Two big features were added as part of this:
* `File:New` handler registration: Plugins can now register themselves with the New menu without going through the extra work of creating a menu item, with only one line: `PluginManager.RegisterNewHandler(this, "Script");`
* View State saving: Another Visual Studio-inspired feature - When a project is closed, the view state of open files is saved in the .ssuser file.  When you load it back up later, you can resume right where you left off!

**Comment by fatcerberus** [comment]
Also it occurs to me that in the end, I basically ended up reimplementing EditorObject wholesale.  My version is more elegant though, I think.

One thing I noticed: Because DocumentView is abstract, controls derived from it can't be shown in the form designer (VS needs to instantiate it).  I originally did this to force plugins to implement Save/Load methods, but the lack of designer support is an issue.  I think I'll change it tomorrow so that Save and Load will throw a `NotImplementedException` if you don't override them.

**Comment by fatcerberus** [comment]
Okay, I've merged the changes into master.  I've been testing for a while and no issues have cropped up, so I figured it would be safe to go ahead.
