### ISSUE TITLE
Sphere Studio Build Pipeline tracker

### ISSUE THREAD

**Issue by fatcerberus** [Radnen/spherestudio#50]
The build process, from Sphere Studio's point of view, would consist of:
- Collect data about the project: Source path, `dist` directory path, name, author, etc.
- Set up a JavaScript environment similar to what Sphere itself does, with a minimal set of tools to make build scripts easier to write.  A global variable `source` will be provided, allowing access to the project.
- Run `ssbuild.js` in the project directory.  If this file doesn't exist, a default build script will be used which simply writes out the `game.sgm` file in the same directory as the project.

This allows ultimate flexibility for the build process.

To avoid interruptions, the build should be run on a separate thread with a pane docked to the bottom of the main window showing progress.

**Comment by fatcerberus** [comment]
As an example, the most basic Sphere build script could be:
```javascript
Print("Writing game.sgm");
var sgm = new TextFile(source.path + "game.sgm");
sgm.write("name=" + source.name);
sgm.write("author=" + source.author);
// etc.
sgm.close();
```

Like Sphere, there will be a RequireScript function to pull in system scripts, such as Link.

**Comment by fatcerberus** [comment]
I'm thinking we're going to have to have two build processes for Sphere: one for the new layout including `dist/`, and one for the legacy setup where nothing is copied and game.sgm is created directly in the project directory.  This would allow opening old Sphere projects and managing them with Sphere Studio, as a direct replacement for the classic editor.

Alternatively, when a game.sgm is opened instead of an .ssproj, the project could be reorganized on the fly to work with the new setup.  This might be better, but would of course be more work to implement.

As for the new format, I imagine a structure like this:

(project dir)
+ dist - created by build
+ assets - copied as-is to dist
+ src

And then any other subdirectories would be controlled by the build system (the stock build would ignore them).  

`src` gets its own directory because this allows the build system to treat it separately.  Whereas assets are just copied with no further processing, scripts can be processed, e.g. with minification, obfuscation, etc.

**Comment by Radnen** [comment]
Well, I say that assets may have a processor attached to them. Fonts can be generated, so can sprite sheets. Maybe there is a GUI generator that turns a specification into code, or perhaps sounds generated in a sfxr like fashion. Maybe map tiles are pruned and tilesets optimized. Perhaps spriteset directions are combined or maybe individual images turn into spritesets.

There's many things that can happen to some assets besides just "copying if newer". It doesn't have to be complicated, I mean the default used 90% of the time is just that - copying. But, if you set an option to use 'spritesheet.js' on a folder,then perhaps the contents of that folder are first funneled through that script.

The system would be generic enough that it doesn't matter if a script, an image or whatever is piped through the processors. It's all part of the build. But as for the folders, it's good to distinctly lay out `dist/` `src/` and `assets/`

**Comment by fatcerberus** [comment]
Oh, naturally, a lot of things may have a processor attached to them.  I didn't fully communicate my intent--I just meant that there would be one folder which with the default Sphere build had the semantics of "copy everything in here as is, preserving the subfolder tree".  I picked "assets" for the name of that folder, but it could be anything, really.

The build process will be able to be customized easily by having a `build.js` in the project directory, I was more talking about the default build script above.  One step at a time and all. :-)

**Comment by fatcerberus** [comment]
The first draft of the build pipeline has been committed to master.  The default build script maintains compatibility with the old editor as far as possible, custom builds will currently require a `build.js` in the project directory.

**Comment by fatcerberus** [comment]
I'm thinking that once I get Cell whipped into usable shape, I might rework the pipeline to use it instead of having all the bindings built into the IDE.  Cell will also have SPK support, so the SPK plugin wouldn't be needed this way and it could just be an optional part of the build process.

**Comment by fatcerberus** [comment]
Build support is provided through Compiler plugins in the recent overhaul:
https://github.com/Radnen/spherestudio/commit/cb8727ae8436ac0a39dc4682cc40b3c861361050

Going to leave this one open for 2.0 though, it might be worthwhile to make an official Jurassic-based compiler plugin at some point.  Either that or bundle with Cell once it's more mature.

**Comment by fatcerberus** [comment]
A lot happened in 2 years: Cell has become the official Sphere compiler, so that's the preferred option to use for a build pipeline.  In fact Cell *is* the default compiler in miniSphere installations.  So this can be considered officially closed now, I think. 😁
